// flow-typed signature: ff047fc415bd36a2fc9f503b35d856f3
// flow-typed version: <<STUB>>/apiai_v^2.0.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apiai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apiai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apiai/module/apiai' {
  declare module.exports: any;
}

declare module 'apiai/module/query_request' {
  declare module.exports: any;
}

declare module 'apiai/module/request' {
  declare module.exports: any;
}

declare module 'apiai/module/text_request' {
  declare module.exports: any;
}

declare module 'apiai/module/user_entities_request' {
  declare module.exports: any;
}

declare module 'apiai/module/voice_request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apiai/index' {
  declare module.exports: $Exports<'apiai'>;
}
declare module 'apiai/index.js' {
  declare module.exports: $Exports<'apiai'>;
}
declare module 'apiai/module/apiai.js' {
  declare module.exports: $Exports<'apiai/module/apiai'>;
}
declare module 'apiai/module/query_request.js' {
  declare module.exports: $Exports<'apiai/module/query_request'>;
}
declare module 'apiai/module/request.js' {
  declare module.exports: $Exports<'apiai/module/request'>;
}
declare module 'apiai/module/text_request.js' {
  declare module.exports: $Exports<'apiai/module/text_request'>;
}
declare module 'apiai/module/user_entities_request.js' {
  declare module.exports: $Exports<'apiai/module/user_entities_request'>;
}
declare module 'apiai/module/voice_request.js' {
  declare module.exports: $Exports<'apiai/module/voice_request'>;
}
