// flow-typed signature: 6f838010dd2ae6f6c156f92fa8feeabe
// flow-typed version: <<STUB>>/idle-js_v^0.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idle-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'idle-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idle-js/dist/idle' {
  declare module.exports: any;
}

declare module 'idle-js/dist/idle.min' {
  declare module.exports: any;
}

declare module 'idle-js/example/webpack/bundle' {
  declare module.exports: any;
}

declare module 'idle-js/example/webpack/entry' {
  declare module.exports: any;
}

declare module 'idle-js/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'idle-js/src/idle' {
  declare module.exports: any;
}

declare module 'idle-js/test/setup/browser' {
  declare module.exports: any;
}

declare module 'idle-js/test/setup/node' {
  declare module.exports: any;
}

declare module 'idle-js/test/setup/setup' {
  declare module.exports: any;
}

declare module 'idle-js/test/unit/idle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idle-js/dist/idle.js' {
  declare module.exports: $Exports<'idle-js/dist/idle'>;
}
declare module 'idle-js/dist/idle.min.js' {
  declare module.exports: $Exports<'idle-js/dist/idle.min'>;
}
declare module 'idle-js/example/webpack/bundle.js' {
  declare module.exports: $Exports<'idle-js/example/webpack/bundle'>;
}
declare module 'idle-js/example/webpack/entry.js' {
  declare module.exports: $Exports<'idle-js/example/webpack/entry'>;
}
declare module 'idle-js/gulpfile.babel.js' {
  declare module.exports: $Exports<'idle-js/gulpfile.babel'>;
}
declare module 'idle-js/src/idle.js' {
  declare module.exports: $Exports<'idle-js/src/idle'>;
}
declare module 'idle-js/test/setup/browser.js' {
  declare module.exports: $Exports<'idle-js/test/setup/browser'>;
}
declare module 'idle-js/test/setup/node.js' {
  declare module.exports: $Exports<'idle-js/test/setup/node'>;
}
declare module 'idle-js/test/setup/setup.js' {
  declare module.exports: $Exports<'idle-js/test/setup/setup'>;
}
declare module 'idle-js/test/unit/idle.js' {
  declare module.exports: $Exports<'idle-js/test/unit/idle'>;
}
